p8105\_hw2\_yw3236
================
Yishan Wang
2018-10-01

Problem 1
=========

### Read and clean the data

-   Retain line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance.

-   Convert the entry variable from character (`YES` vs `NO`) to a logical variable.

``` r
transit_data = 
  read_csv(file = "./NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(., "line", "station_name", "station_latitude", "station_longitude", "route1":"route11", "entry", "vending", "entrance_type", "ada") %>%
  mutate(., entry = recode(entry, YES = TRUE, NO = FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

### A short paragraph about this dataset

The variables that dataset contains are `line`, `station_name`, `station_latitude`, `station_longitude`, `rout1` to `rout11`, `entry`, `vending`, `entrence_type`, `ada`. After reading the dataset to R, I used `janitor::clean_names()` to clean the variable names. Then I used `select` to selecte the variables that I want to keep in the dataset and delete other unwanted variables. Lastly, I used `mutate` and `recode` to convert the `entry` from character variable to logical variable. The dimension of the resulting dataset is 1868 x 19. Yes, the data are tidy.

### Answering the questons

``` r
nrow(distinct(transit_data, line, station_name))
```

    ## [1] 465

The number of the distinct stations are 465.

``` r
station_ada = 
  distinct(transit_data, line, station_name, .keep_all = TRUE) %>%
  dplyr::filter(., ada == TRUE)
nrow(station_ada)
```

    ## [1] 84

There are 84 stations that are ADA compliant.

``` r
vending_no = transit_data %>%
  dplyr::filter(., vending == 'NO')

prop = nrow(dplyr::filter(vending_no, entry == TRUE)) / nrow(vending_no)
prop
```

    ## [1] 0.3770492

The proportion of station entrances / exists without vending allow entrance is 0.3770492.

``` r
reform_data = transit_data %>%
  gather(., key = route_num, value = route_name, route1:route11) %>%
  dplyr::filter(., route_name == 'A')

dist_station_serve_A = distinct(reform_data, line, station_name, .keep_all = TRUE)
nrow(dist_station_serve_A)
```

    ## [1] 60

``` r
dist_ada_station_serve_A = dplyr::filter(dist_station_serve_A, ada == TRUE)
nrow(dist_ada_station_serve_A)
```

    ## [1] 17

There are 60 distinct stations serve A train, and 17 of them are ADA compliant.

Problem 2
=========

### Read and clean the Mr. Trash Wheel sheet

-   Specify the sheet in the Excel file and to omit columns containing notes.

-   Omit rows that do not include dumpster-specific data.

-   Rounds the number of sports balls to the nearest integer and converts the result to an integer variable.

``` r
trash_data = 
  readxl::read_excel("./HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 1, range = cellranger::cell_cols("A:N")) %>% 
  janitor::clean_names() %>%
  dplyr::filter(., !is.na(dumpster)) %>%
  mutate(sports_balls = round(sports_balls)) %>%
  mutate(sports_balls = as.integer(.$sports_balls))
```
